# Generated by Django 5.0.1 on 2026-08-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='last_login_method',
            field=models.CharField(blank=True, help_text="Tracks whether the user last logged in via 'session' or 'token'", max_length=20, null=True),
        ),
    ]
