# Generated by Django 5.0.1 on 2026-08-17 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_systemuser_last_login_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='last_login_method',
        ),
    ]
