# Generated by Django 5.0.1 on 2026-06-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerOrders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dateSince',
            field=models.DateField(blank=True, null=True),
        ),
    ]
