# Generated by Django 5.0.1 on 2026-06-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerOrders', '0002_customer_datesince'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.AlterModelTable(
            name='order',
            table='customer_order',
        ),
    ]
