# Generated by Django 5.0.1 on 2026-07-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerOrders', '0004_systemuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemUser',
        ),
    ]
